/*
 * ============================================================================
 *
 *  Zombie:Reloaded
 *
 *  File:          infect.inc
 *  Type:          Core
 *  Description:   Client infection functions.
 *
 *  Copyright (C) 2009-2013  Greyscale, Richard Helgeby
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * ============================================================================
 */

#if defined REQUIRE_PLUGIN
 #define TEMP_REQUIRE_PLUGIN
 #undef REQUIRE_PLUGIN
#endif

#tryinclude "AFKManager.inc"
#tryinclude "TeamManager.inc"

/* Restore old REQUIRE_PLUGIN value if necessary */
#if defined TEMP_REQUIRE_PLUGIN
 #define REQUIRE_PLUGIN
 #undef TEMP_REQUIRE_PLUGIN
#endif

bool g_AFKManagerLoaded = false;
bool g_TeamManagerLoaded = false;

/**
 * @section Explosion flags.
 */
#define EXP_NODAMAGE               1
#define EXP_REPEATABLE             2
#define EXP_NOFIREBALL             4
#define EXP_NOSMOKE                8
#define EXP_NODECAL               16
#define EXP_NOSPARKS              32
#define EXP_NOSOUND               64
#define EXP_RANDOMORIENTATION    128
#define EXP_NOFIREBALLSMOKE      256
#define EXP_NOPARTICLES          512
#define EXP_NODLIGHTS           1024
#define EXP_NOCLAMPMIN          2048
#define EXP_NOCLAMPMAX          4096
/**
 * @endsection
 */
 
 /**
 * @section Other defines.
 */
 #define MAX_EVENT_LENGTH 32
/**
 * @endsection
 */

/**
 * @section Global variables to store infect timer handles.
 */
Handle g_tInfect = null;
Handle g_tInfectCountdown = null;
/**
 * @endsection
 */

/**
 * Infection countdown data pack.
 */
DataPack g_hInfectCountdownData = null;

/**
 * Array for flagging client as zombie.
 */
bool g_bZombie[MAXPLAYERS + 1];

/**
 * Array for flagging client to be protected.
 */
bool g_bInfectImmune[MAXPLAYERS + 1];

/**
 * Array for storing client mother zombie last flag.
 */
bool g_bInfectMotherLast[MAXPLAYERS + 1];

/**
 * SteamID cache for storing client mother zombie protection status.
 */
ArrayList g_hInfectMotherCycle = null;
ArrayList g_hInfectMotherCycleRTD = null;

/**
 * Available mother zombie infection modes.
 */
enum InfectMode
{
    InfectMode_Invalid = -1,    /** Invalid mode, used by validators. */
    InfectMode_Dynamic,         /** Every n-th player is infected. */
    InfectMode_Absolute,        /** Keep n humans (negative n) or infect n zombies. */
    InfectMode_Range            /** An absolute number of zombies infected (min to max). */
}

/**
 * All plugins have finished loading.
 */
void InfectOnAllPluginsLoaded()
{
    #if defined _AFKManager_Included
    g_AFKManagerLoaded = LibraryExists("AFKManager");
    LogMessage("AFKManager: %s", (g_AFKManagerLoaded ? "loaded" : "not loaded"));
    #endif

    #if defined _TeamManager_include
    g_TeamManagerLoaded = LibraryExists("TeamManager");
    LogMessage("TeamManager: %s", (g_TeamManagerLoaded ? "loaded" : "not loaded"));
    #endif
}

/**
 * A library was added.
 */
void InfectOnLibraryAdded(const char[] name)
{
    if (strcmp(name, "AFKManager", false) == 0)
    {
        // AFKManager loaded.
        g_AFKManagerLoaded = true;
    }
    else if (strcmp(name, "TeamManager", false) == 0)
    {
        // TeamManager loaded.
        g_TeamManagerLoaded = true;
    }
}

/**
 * A library was removed.
 */
void InfectOnLibraryRemoved(const char[] name)
{
    if (strcmp(name, "AFKManager", false) == 0)
    {
        // AFKManager unloaded.
        g_AFKManagerLoaded = false;
    }
    else if (strcmp(name, "TeamManager") == 0)
    {
        // TeamManager unloaded.
        g_TeamManagerLoaded = false;
    }
}

/**
 * Map is ending.
 */
void InfectOnMapEnd()
{
    // Reset timers. Infect timers are invalidated on a map change if they are
    // still running.
    ZREndTimer(g_tInfect);
    ZREndTimer(g_tInfectCountdown);
    InfectStopCountdown();

    // Clear mother zombie round-robin cycle storage.
    SteamidCacheReset(g_hInfectMotherCycle);
    SteamidCacheReset(g_hInfectMotherCycleRTD);
}

/**
 * Loads downloadable content data for infect module.
 */
void InfectLoad()
{
    // Create mother zombie round-robin cycle storage.
    g_hInfectMotherCycle = SteamidCacheCreate();
   	
    g_hInfectMotherCycleRTD = SteamidCacheCreate();
    
    // Initialize mother zombie overrides
    ResetMotherZombieOverrides();
}

/**
 * Create commands specific to infect here.
 */
void InfectOnCommandsCreate()
{
    RegConsoleCmd("zr_infect", InfectInfectCommand, "Infect a client. Usage: zr_infect <filter> [respawn - 1/0]");
    RegConsoleCmd("zr_human", InfectHumanCommand, "Turn a client into a human. Usage: zr_human <filter> [respawn - 1/0]");
}

/**
 * Calculates the weight of a player for mother zombie selection.
 * Higher weight means higher chance of being selected.
 *
 * @param client    The client index.
 * @return          The weight value (0.0-1.0).
 */
float CalculatePlayerWeight(int client)
{
    float weight;

    // If player is not in RTD cycle, they never were mother zombie
    if (!SteamidCacheClientExists(g_hInfectMotherCycleRTD, client))
    {
        weight = 1.0 - g_hCvarsList.CVAR_INFECT_MZOMBIE_WEIGHT_NEW.FloatValue;
    }
    // If player is in RTD cycle but not in main cycle
    else if (!SteamidCacheClientExists(g_hInfectMotherCycle, client))
    {
        weight = 1.0 - g_hCvarsList.CVAR_INFECT_MZOMBIE_WEIGHT_RTD.FloatValue;
    }
    // Player is in both cycles
    else
    {
        weight = 1.0 - g_hCvarsList.CVAR_INFECT_MZOMBIE_WEIGHT_BOTH.FloatValue;
    }

    // Ensure weight is not negative
    return (weight < 0.0) ? 0.0 : weight;
}

/**
 * Client is joining the server.
 *
 * @param client    The client index.
 */
void InfectClientInit(int client)
{
    // Reset infect immunity flag.
    g_bInfectImmune[client] = false;

    // Reset mother zombie last flag.
    g_bInfectMotherLast[client] = false;

    bool infectroundrobinrtd = g_hCvarsList.CVAR_INFECT_ROUND_ROBIN_RTD.BoolValue;
    if (infectroundrobinrtd && !SteamidCacheClientExists(g_hInfectMotherCycleRTD, client))
    {
        SteamidCacheAddClient(g_hInfectMotherCycleRTD, client);

        int players = 0;
        int playersInList = 0;
        for (int x = 1; x <= MaxClients; x++)
        {
            if (!IsClientInGame(x))
                continue;

            #if defined _AFKManager_Included
            if (g_AFKManagerLoaded)
            {
                if (!IsFakeClient(x) && GetClientIdleTime(x) > 3 * 60)
                    continue;
            }
            #endif

            players++;

            if (SteamidCacheClientExists(g_hInfectMotherCycle, x))
                playersInList++;
        }

        if (players && playersInList)
        {
            // Calculate player's weight
            float playerWeight = CalculatePlayerWeight(client);
            
            // Adjust probability based on weight
            // Higher weight means lower chance of being added
            float mzombiechance = (float(playersInList) / float(players)) * (1.0 - playerWeight);
            float dice = GetRandomFloat();

            if (dice < mzombiechance)
                SteamidCacheAddClient(g_hInfectMotherCycle, client);
        }
    }
}

/**
 * Client is leaving the server.
 *
 * @param client    The client index.
 */
void InfectOnClientDisconnect(int client)
{
    // Reset mother zombie attributes when client disconnects
    ClassResetMotherZombieAttributes(client);
    
    // If client is still connecting, then stop.
    if (!IsClientInGame(client))
    {
        return;
    }

    // If zombie hasn't spawned, then stop.
    if (!InfectHasZombieSpawned())
    {
        return;
    }

    // If client is dead, then stop.
    if (!IsPlayerAlive(client))
    {
        return;
    }

    // Initialize count variables
    int zombiecount;
    int humancount;

    // Count valid clients.
    ZRCountValidClients(zombiecount, humancount);

    // If client is a human.
    if (InfectIsClientHuman(client))
    {
        // If there are other humans (ignoring this human), then stop.
        if (humancount > 1)
        {
            return;
        }

        // If there are no more clients in the server, then stop.
        if (!ZRTeamHasClients(CS_TEAM_T))
        {
            return;
        }

        // Manually terminate round.
        RoundEndTerminateRound(ROUNDEND_DELAY, ZombiesWin);

        return;
    }

    // We know here that player is a zombie.

    // If there is 1 or less humans, then stop.
    if (humancount <= 1)
    {
        return;
    }

    // If there are other zombies (ignoring this zombie), then stop.
    if (zombiecount - 1)
    {
        return;
    }

    // Create eligible player list.
    ArrayList arrayEligibleClients = new ArrayList();

    // Create eligible client list, with no mother infect immunities
    int eligibleclients = ZRCreateEligibleClientList(arrayEligibleClients, true, true, true);

    // If there are no eligible client's then stop.
    if (!eligibleclients)
    {
        // Destroy handle.
        delete arrayEligibleClients;
        return;
    }

    // Get a random valid array index.
    int randindex = Math_GetRandomInt(0, eligibleclients - 1);

    // Get the client stored in the random array index.
    int randclient = arrayEligibleClients.Get(randindex);

    // Infect player.
    InfectHumanToZombie(randclient);

    // Force ztele the client chosen to replace disonnecting zombie
    bool fztelenew = ZTele_ChosenClientReplaceDisconnected();
    if (fztelenew)
        ZTele_TeleportClient(randclient);

    // Tell client they have been randomly been chosen to replace disconnecting zombie.
    TranslationPrintToChat(randclient, "Infect disconnect");

    // Destroy handle.
    delete arrayEligibleClients;
}

/**
 * Client is joining a team.
 *
 * @param client    The client index.
 * @param team      The team index.
 */
void InfectOnClientTeam(int client, int team)
{
    // If client isn't joining spec, then stop.
    if (team != CS_TEAM_SPECTATOR)
    {
        return;
    }

    // Disable zombie flag on client.
    g_bZombie[client] = false;
}

/**
 * Client is spawning into the game.
 *
 * @param client    The client index.
 */
void InfectOnClientSpawn(int client)
{
    // Reset mother zombie attributes when client spawns
    ClassResetMotherZombieAttributes(client);

    // Disable zombie flag on client.
    g_bZombie[client] = false;

    // Check if client is spawning on the terrorists team.
    if (ZRIsClientOnTeam(client, CS_TEAM_T) && InfectHasZombieSpawned())
    {
        CS_SwitchTeam(client, CS_TEAM_CT);
        CS_RespawnPlayer(client);
    }

    // Unglitch kevlar, set last hitgroup to HITGROUP_GENERIC
    ToolsSetClientLastHitGroup(client, HITGROUP_GENERIC);

    // Forward event to modules.
    ZSpawnOnClientSpawn(client);
}

/**
 * Client has been killed.
 *
 * @param client    The client index.
 * @param attacker  The attacker index.
 */
void InfectOnClientDeath(int client, int attacker)
{
    // If attacker isn't valid, then stop.
    if (!ZRIsClientValid(attacker))
    {
        return;
    }

    // If attacker isn't a human, then stop.
    if (!InfectIsClientHuman(attacker))
    {
        return;
    }

    // If client isn't a zombie, then stop.
    if (!InfectIsClientInfected(client))
    {
        return;
    }

    // Add kill bonus to attacker's score.
    int bonus = ClassGetKillBonus(client);
    int score = ToolsClientScore(attacker, true, false);
    ToolsClientScore(attacker, true, true, score + bonus);
}

/**
 * Client has been hurt.
 *
 * @param client        The client index.
 * @param attacker      The attacker index.
 * @param weapon        The weapon used.
 */
void InfectOnClientHurt(int client, int attacker, const char[] weapon)
{
    // If attacker isn't valid, then stop.
    if (!ZRIsClientValid(attacker))
    {
        return;
    }

    // If client isn't a human, then stop.
    if (!InfectIsClientHuman(client))
    {
        return;
    }

    // Attacker isn't a zombie, then stop.
    if (!InfectIsClientInfected(attacker))
    {
        return;
    }

    // If client has infect immunity, then stop.
    if (g_bInfectImmune[client])
    {
        return;
    }

    // If weapon isn't a knife, then stop.
    if (strcmp(weapon, "knife", false) != 0 && strcmp(weapon, "bayonet", false) != 0)
    {
        return;
    }

    // Check if the immunity module is handling the infection.
    if (ImmunityOnClientInfect(client, attacker))
    {
        //PrintToChatAll("InfectOnClientHurt - Infect blocked.");
        return;
    }

    // Infect client.
    InfectHumanToZombie(client, attacker);
}

/**
 * The round is starting.
 */
void InfectOnRoundStart()
{
    // Stop infect timers if running.
    ZREndTimer(g_tInfect);
    ZREndTimer(g_tInfectCountdown);

    // Tell plugin there are no zombies.
    g_bZombieSpawned = false;
}

/**
 * The freeze time is ending.
 */
void InfectOnRoundFreezeEnd()
{
    // Stop infect timers if running.
    ZREndTimer(g_tInfect);
    ZREndTimer(g_tInfectCountdown);

    // If the zombie has spawned already (had to be through admin) then stop.
    if (InfectHasZombieSpawned())
    {
        return;
    }

    // Warmup
    #if defined _TeamManager_include
    if (g_TeamManagerLoaded && TeamManager_HasWarmup() && TeamManager_InWarmup())
    {
        return;
    }
    #endif

    // Get min and max times.
    float infectspawntimemin = g_hCvarsList.CVAR_INFECT_SPAWNTIME_MIN.FloatValue;
    float infectspawntimemax = g_hCvarsList.CVAR_INFECT_SPAWNTIME_MAX.FloatValue;

    // Pick random time between min and max.
    float randomtime = GetRandomFloat(infectspawntimemin, infectspawntimemax);

    g_tInfect = CreateTimer(randomtime, InfectMotherZombie, _, TIMER_FLAG_NO_MAPCHANGE);

    // Check cvar and start a countdown timer if enabled.
    bool countdown = g_hCvarsList.CVAR_INFECT_MZOMBIE_COUNTDOWN.BoolValue;
    if (countdown && randomtime > 1.0)
    {
        // Stop old countdown timer, if it exists.
        InfectStopCountdown();

        // Store the time until infection, and initialize the counter.
        g_hInfectCountdownData = new DataPack();
        g_hInfectCountdownData.WriteFloat(randomtime);
        g_hInfectCountdownData.WriteFloat(0.0);
        g_tInfectCountdown = CreateTimer(1.0, InfectCountdown, _, TIMER_REPEAT | TIMER_FLAG_NO_MAPCHANGE);

        // Display initial tick.
        InfectCountdown(g_tInfectCountdown);
    }
}

/**
 * The round is ending.
 */
public Action InfectOnRoundEnd(Handle Timer)
{
    // Stop infect timers if running.
    ZREndTimer(g_tInfect);
    ZREndTimer(g_tInfectCountdown);

    // x = client index.
    for (int x = 1; x <= MaxClients; x++)
    {
        // Disable zombie flag on client.
        g_bZombie[x] = false;
    }
    return Plugin_Continue;
}

/**
 * Timer callback, chooses mother zombies.
 *
 * @param timer     The timer handle.
 */
public Action InfectMotherZombie(Handle timer)
{
    // Reset timer handle.
    g_tInfect = null;

    // Warmup
    #if defined _TeamManager_include
    if (g_TeamManagerLoaded && TeamManager_HasWarmup() && TeamManager_InWarmup())
    {
        return Plugin_Continue;
    }
    #endif

    // Create eligible player list.
    ArrayList arrayEligibleClients = new ArrayList();
    int eligibleclients = ZRCreateEligibleClientList(arrayEligibleClients, true, true, true, true);

    // If there are no eligible client's then stop.
    if (!eligibleclients)
    {
        // Destroy handle.
        delete arrayEligibleClients;
        return Plugin_Continue;
    }

    // Move all clients to CT.
    InfectMoveAllToCT();

    int mothercount;
    int ratio = g_hCvarsList.CVAR_INFECT_MZOMBIE_RATIO.IntValue;
    int min = g_hCvarsList.CVAR_INFECT_MZOMBIE_MIN.IntValue;
    int max = g_hCvarsList.CVAR_INFECT_MZOMBIE_MAX.IntValue;

    // Count valid human clients.
    int humancount;
    ZRCountValidClients(_, humancount, _, true);

    // Get and validate infection mode. This will also log a warning on error.
    InfectMode mode = InfectGetModeOrFail();

    // Apply infection mode.
    switch (mode)
    {
        case InfectMode_Invalid:
        {
            // Validation failed. Fall back to one mother zombie.
            mothercount = 1;
        }
        case InfectMode_Dynamic:
        {
            // Dynamic mode. Every n-th player is infected.

            // A ratio of 0 will infect one zombie (to keep backwards compatibility).
            if (ratio == 0)
            {
                mothercount = 1;
            }

            // Calculate number of zombies to infect.
            mothercount = RoundToNearest(float(humancount) / ratio);

            // Require at least one mother zombie.
            if (mothercount == 0)
            {
                mothercount = 1;
            }
        }
        case InfectMode_Absolute:
        {
            if (ratio > 0)
            {
                // Infect n humans.
                mothercount = ratio;
            }
            else
            {
                // Infect all but n humans. Since ratio already is negative
                // just add the numbers. (Zero ratio is catched by validator.)
                mothercount = humancount + ratio;

                // Force at least one mother zombie.
                if (mothercount == 0)
                {
                    mothercount = 1;
                }
            }
        }
        case InfectMode_Range:
        {
            // Get a random number between the range.
            mothercount = Math_GetRandomInt(min, max);
        }
    }

    bool infectroundrobin = g_hCvarsList.CVAR_INFECT_ROUND_ROBIN.BoolValue;
    int candidatesMain = 0;
    int candidatesAlt = 0;
    ArrayList aCandidatesMain = new ArrayList();
    ArrayList aCandidatesAlt = new ArrayList();
    for (int n = 0; n < eligibleclients; n++)
    {
        // Get the client stored in the array index.
        int client = arrayEligibleClients.Get(n);

        // If client hasn't been chosen last round.
        if (!g_bInfectMotherLast[client])
        {
            // If client hasn't been chosen this cycle, put into aCandidatesMain array.
            if (!infectroundrobin || !SteamidCacheClientExists(g_hInfectMotherCycle, client))
            {
                aCandidatesMain.Push(client);
                candidatesMain++;
            }

            // Else put into aCandidatesAlt array.
            else
            {
                aCandidatesAlt.Push(client);
                candidatesAlt++;
            }
        }
    }

    // Remove mother zombie last flag from all players.
    for (int client = 0; client <= MaxClients; client++)
    {
        g_bInfectMotherLast[client] = false;
    }

    bool resetcycle;

    // Infect players.
    int infected = 0;
    while (infected < mothercount)
    {
        // Infect one of the main candidates.
        if (candidatesMain)
        {
            // Get a random array index.
            int i = Math_GetRandomInt(0, candidatesMain - 1);

            // Get the client stored in the random array index.
            int client = aCandidatesMain.Get(i);

            // Infect player.
            if (InfectHumanToZombie(client, _, true))
                infected++;

            // Remove player from eligible client list.
            aCandidatesMain.Erase(i);
            candidatesMain--;
        }
        else
        {
            // No main candidates, reset the mother zombie cycle now before infecting anyone else.
            if (infectroundrobin && !resetcycle)
            {
                resetcycle = true;
                // Clear mother zombie round-robin cycle storage.
                SteamidCacheReset(g_hInfectMotherCycle);
                SteamidCacheReset(g_hInfectMotherCycleRTD);

                // Announce start of new cycle
                TranslationPrintToChatAll(true, false, "Mother zombie infect cycle reset");
            }

            // Infect one of the alternate candidates.
            if (candidatesAlt)
            {
                // Get a random array index.
                int i = Math_GetRandomInt(0, candidatesAlt - 1);

                // Get the client stored in the random array index.
                int client = aCandidatesAlt.Get(i);

                // Infect player.
                if (InfectHumanToZombie(client, _, true))
                    infected++;

                // Remove player from eligible client list.
                aCandidatesAlt.Erase(i);
                candidatesAlt--;
            }
            else // We have no candidates at all, abort!
            {
                break;
            }
        }
    }

    // Mother zombies have been infected.
    g_bZombieSpawned = true;

    // Destroy client list.
    delete arrayEligibleClients;
    delete aCandidatesMain;
    delete aCandidatesAlt;

    return Plugin_Continue;
}

/**
 * Moves all alive clients to the CT team.
 */
void InfectMoveAllToCT()
{
    // Move all clients to CT
    for (int client = 1; client <= MaxClients; client++)
    {
        // If client isn't in-game, then stop.
        if (!IsClientInGame(client))
        {
            continue;
        }

        // If client is dead, then stop.
        if (!IsPlayerAlive(client))
        {
            continue;
        }

        // Switch client to CT team.
        CS_SwitchTeam(client, CS_TEAM_CT);
    }
}

/**
 * Timer callback, displays countdown to clients.
 *
 * @param timer     The timer handle.
 */
public Action InfectCountdown(Handle timer)
{
    if (!g_hCvarsList.CVAR_INFECT_MZOMBIE_COUNTDOWN.BoolValue)
    {
        InfectStopCountdown();
        return Plugin_Stop;
    }

    // Read the info from the datapack.
    g_hInfectCountdownData.Reset();
    float length = g_hInfectCountdownData.ReadFloat();
    float counter = g_hInfectCountdownData.ReadFloat();

    // Check if the countdown has finished.
    if (counter >= length)
    {
        InfectStopCountdown();
        return Plugin_Stop;
    }

    // Ask plugin API if timer should be shown.
    if (APIOnInfectCountdown() == Plugin_Continue)
    {
        // Print the countdown text to the clients.
        TranslationPrintCenterTextAll(false, "Infect countdown", RoundToNearest(length - counter));

        if (g_hCvarsList.CVAR_INFECT_MZOMBIE_RESPAWN_WARNING.BoolValue && !g_hCvarsList.CVAR_INFECT_MZOMBIE_RESPAWN.BoolValue)
        {
            PrintHintTextToAll("%t", "Infect spawning warning");
        }

        float countdownvolume = SEffects_GetVolume();
        int countdown = RoundToNearest(length - counter);
        int iInfectCountdownSounds = SEffects_GetMax(Countdown);
        if (countdownvolume > 0.0 && iInfectCountdownSounds != 0 && countdown > 0 && countdown <= iInfectCountdownSounds)
        {
            char soundpath[PLATFORM_MAX_PATH];
            SEffects_GetPath(soundpath, Countdown);
            Format(soundpath, SOUND_MAX_PATH, soundpath, countdown);

            for (int x = 1; x <= MaxClients; x++)
            {
                if (IsClientInGame(x) && zfZSoundVolume[x] > 0)
                {
                    EmitSoundToClient(x, soundpath, _, _, SNDLEVEL_NORMAL, _, zfZSoundVolume[x]);
                }
            }
        }
    }

    counter++;

    // Write the new counter value to the datapack.
    g_hInfectCountdownData.Reset();
    g_hInfectCountdownData.WriteFloat(length);
    g_hInfectCountdownData.WriteFloat(counter);

    return Plugin_Continue;
}

/**
 * Stops the infection countdown timer.
 */
void InfectStopCountdown()
{
    // Kill the timer.
    ZREndTimer(g_tInfectCountdown);

    // Destroy data pack.
    delete g_hInfectCountdownData;
}

/**
 * Infects a client. Execute events, sets attributes and flags that indicate
 * that the client is a zombie.
 *
 * @param client            The client to infect.
 * @param attacker          (Optional) The attacker who did the infect.
 * @param motherinfect      (Optional) Indicates a mother zombie infect.
 * @param respawnoverride   (Optional) Set to true to override respawn cvar.
 * @param respawn           (Optional) Value to override with.
 */
bool InfectHumanToZombie(int client, int attacker = -1, bool motherinfect = false, bool respawnoverride = false, bool respawn = false)
{
    if (!g_bRoundFullyStarted)
    {
        return false;
    }

    // Forward pre-event to modules.
    Action result = APIOnClientInfect(client, attacker, motherinfect, respawnoverride, respawn);

    // Check if infection should be blocked.
    if (result == Plugin_Handled)
    {
        return false;
    }

    // Reset mother zombie attributes when client becomes zombie
    ClassResetMotherZombieAttributes(client);

    // Mark player as zombie.
    g_bZombie[client] = true;

    // Check if consecutive infection protection is enabled.
    bool infectconsecutiveblock = g_hCvarsList.CVAR_INFECT_CONSECUTIVE_BLOCK.BoolValue;
    bool infectroundrobin = g_hCvarsList.CVAR_INFECT_ROUND_ROBIN.BoolValue;

    // If this is a mother infect, update the mother zombie protection status
    if (motherinfect)
    {
        g_bInfectMotherLast[client] = infectconsecutiveblock;
        if (infectroundrobin)
        {
            SteamidCacheAddClient(g_hInfectMotherCycle, client);
        }
    }

    // Apply effects.
    InfectFireEffects(client);

    // Stop coundown, if running.
    InfectStopCountdown();

    // If attacker is valid, then continue.
    if (ZRIsClientValid(attacker))
    {
        // Create and send custom player_death event.
        Event event = CreateEvent("player_death");
        if (event != null)
        {
            char eventWeapon[MAX_EVENT_LENGTH];
            g_hCvarsList.CVAR_INFECT_EVENT_WEAPON.GetString(eventWeapon, MAX_EVENT_LENGTH);
            event.SetInt("userid", GetClientUserId(client));
            event.SetInt("attacker", GetClientUserId(attacker));
            event.SetString("weapon", eventWeapon);
            event.Fire(false);
        }

        // Apply score and health gain.
        InfectUpdateScore(attacker, client);
    }

    // Check if weapons drop is enabled.
    bool weaponsdrop = g_hCvarsList.CVAR_INFECT_WEAPONS_DROP.BoolValue;

    // This must be after the event forwarding because it fixes a problem caused by changing models in ClassOnClientInfected.
    // Remove all weapons but knife.
    WeaponsRemoveAllClientWeapons(client, weaponsdrop);

    // Zombie won't be able to use their knife for this amount of time
    float knifecooldown = g_hCvarsList.CVAR_INFECT_KNIFE_COOLDOWN.FloatValue;
    SetEntPropFloat(client, Prop_Send, "m_flNextAttack", GetGameTime() + knifecooldown);

    // Switch the player to terrorists.
    // TODO: A solution to stop confusing bots? Respawn and teleport?
    CS_SwitchTeam(client, CS_TEAM_T);

    // If respawn is enabled, then teleport mother zombie back to spawnpoint.
    if (motherinfect)
    {
        bool zombierespawn = g_hCvarsList.CVAR_INFECT_MZOMBIE_RESPAWN.BoolValue;
        if (zombierespawn)
        {
            ZTele_TeleportClient(client);
        }
    }
    // Check override.
    else
    {
        bool teleport = g_hCvarsList.CVAR_INFECT_TELEPORT.BoolValue;
        if (respawnoverride && respawn)
        {
            ZTele_TeleportClient(client);
        }
        // Teleport to attacker when infected
        else if (teleport && ZRIsClientValid(attacker))
        {
            // Get client's position.
            float clientloc[3];
            GetClientAbsOrigin(attacker, clientloc);

            TeleportEntity(client, clientloc, NULL_VECTOR, NULL_VECTOR);
        }
    }

    // Remove kevlar and helmet
    SetEntProp(client, Prop_Send, "m_ArmorValue", 0, 1);
    SetEntProp(client, Prop_Send, "m_bHasHelmet", 0);

    // Print message to client.
    TranslationPrintToChat(client, "Infect infected");

    // Forward event to modules.
    ClassOnClientInfected(client, motherinfect);
    RoundEndOnClientInfected();
    DamageOnClientInfected(client, motherinfect);
    SEffectsOnClientInfected(client);
    ZTele_OnClientInfected(client);
    ZHPOnClientInfected(client);
    APIOnClientInfected(client, attacker, motherinfect, respawnoverride, respawn);
    ImmunityOnClientInfected(client);
    ZSpawnOnClientInfected(client);

    return true;
}

/**
 * Turns a zombie back into a human. Execute events, sets attributes and flags that indicate
 * that the client is a human.
 *
 * @param client        The client to make human.
 * @param respawn       Teleport client back to spawn if true.
 * @param protect       Start spawn protection on new human.
 */
bool InfectZombieToHuman(int client, bool respawn = false, bool protect = false)
{
    // Forward pre-event to modules.
    Action result = APIOnClientHuman(client, respawn, protect);

    // Check if action should be blocked.
    if (result == Plugin_Handled)
    {
        return false;
    }

    // Reset mother zombie attributes when client becomes human
    ClassResetMotherZombieAttributes(client);

    // Mark player as human.
    g_bZombie[client] = false;

    // Switch the player to counter-terrorists.
    CS_SwitchTeam(client, CS_TEAM_CT);

    // Set client as translation target.
    SetGlobalTransTarget(client);

    // Print message to client.
    TranslationPrintToChat(client, "Infect human");

    // Forward event to modules.
    ClassReloadPlayer(client);
    RoundEndOnClientInfected();
    ZTele_OnClientInfected(client);

    // Remove all knifes.
    WeaponsClearClientWeaponSlot(client, Slot_Melee, false);

    // Give human a new knife. (If you leave the old one there will be glitches with the knife positioning)
    GivePlayerItem(client, "weapon_knife");

    // Check if we should respawn the client.
    if (respawn)
    {
        ZTele_TeleportClient(client);
    }

    // Check if we should spawn protect the client.
    if (protect)
    {
        SpawnProtectStart(client);
    }

    // Unglitch kevlar, set last hitgroup to HITGROUP_GENERIC
    ToolsSetClientLastHitGroup(client, HITGROUP_GENERIC);

    // Forward event to modules.
    SEffectsOnClientHuman(client);
    APIOnClientHumanPost(client, respawn, protect);
    ImmunityOnClientHuman(client);
    ZSpawnOnClientHuman(client);

    return true;
}

/**
 * Updates score for attacker and victim. Applies health gain for attacker.
 */
void InfectUpdateScore(int attacker, int victim)
{
    // Give client's infector a point.
    int score = ToolsClientScore(attacker, true, false);
    ToolsClientScore(attacker, true, true, ++score);

    // Add a death to the zombie's score.
    int deaths = ToolsClientScore(victim, false, false);
    ToolsClientScore(victim, false, true, ++deaths);

    // Apply infect HP gain.
    int healthgain = ClassGetHealthInfectGain(attacker);
    int health = GetClientHealth(attacker);

    // Set attacker's new health.
    SetEntityHealth(attacker, health + healthgain);

    // Forward event to modules.
    ZHPOnHealthInfectGain(attacker);
}

/**
 * Creates effects on a newly infected client.
 *
 * @param client    The client index.
 */
void InfectFireEffects(int client)
{
    // Initialize vector variables.
    float clientloc[3];
    float direction[3] = {0.0, 0.0, 0.0};

    // Get client's position.
    GetClientAbsOrigin(client, clientloc);
    clientloc[2] += 30;

    bool explosion = g_hCvarsList.CVAR_INFECT_EXPLOSION.BoolValue;
    if (explosion)
    {
        // Initialize explosion flags variable.
        int flags;

        // Set "nofireball" flag if fireball is disabled.
        bool fireball = g_hCvarsList.CVAR_INFECT_FIREBALL.BoolValue;
        if (!fireball)
        {
            flags = flags | EXP_NOFIREBALL;
        }

        // Set "nosmoke" flag if smoke is disabled.
        bool smoke = g_hCvarsList.CVAR_INFECT_SMOKE.BoolValue;
        if (!smoke)
        {
            flags = flags | EXP_NOSMOKE;
        }

        // Set "nosparks" flag if sparks are disabled.
        bool sparks = g_hCvarsList.CVAR_INFECT_SPARKS.BoolValue;
        if (!sparks)
        {
            flags = flags | EXP_NOSPARKS;
        }

        // Create explosion at client's origin.
        VEffectsCreateExplosion(clientloc, flags);
    }

    // Emit scream sound if enabled.
    ZombieSoundsScream(client);

    // If energy splash effect is enabled, then continue.
    bool esplash = g_hCvarsList.CVAR_INFECT_ESPLASH.BoolValue;
    if (esplash)
    {
        // Create energy splash effect.
        VEffectsCreateEnergySplash(clientloc, direction, true);
    }

    // If shake effect is enabled, then continue.
    bool shake = g_hCvarsList.CVAR_INFECT_SHAKE.BoolValue;
    if (shake)
    {
        // Get shake info.
        float shakeamp = g_hCvarsList.CVAR_INFECT_SHAKE_AMP.FloatValue;
        float shakefrequency = g_hCvarsList.CVAR_INFECT_SHAKE_FREQUENCY.FloatValue;
        float shakeduration = g_hCvarsList.CVAR_INFECT_SHAKE_DURATION.FloatValue;

        // Shake client's screen.
        VEffectsShakeClientScreen(client, shakeamp, shakefrequency, shakeduration);
    }
}

/**
 * Sends list of clients to infect/human.
 *
 * @param client    The client index.
 */
void InfectMenuClients(int client)
{
    // Create menu handle.
    Menu menu_infect_clients = new Menu(InfectMenuClientsHandle);

    // Set client as translation target.
    SetGlobalTransTarget(client);

    char title[MENU_LINE_TITLE_LENGTH];
    char clientoption[MENU_LINE_REG_LENGTH];
    char clientuserid[8];

    // x = Client index.
    for (int x = 1; x <= MaxClients; x++)
    {
        // If client isn't in-game, then stop.
        if (!IsClientInGame(x))
        {
            continue;
        }

        // If client isn't alive, then stop.
        if (!IsPlayerAlive(x))
        {
            continue;
        }

        // Get client info.
        GetClientName(x, clientoption, sizeof(clientoption));
        IntToString(GetClientUserId(x), clientuserid, sizeof(clientuserid));

        // Append client's current team to the option.
        if (InfectIsClientInfected(x))
        {
            Format(clientoption, sizeof(clientoption), "%s [%t]", clientoption, "Zombie");
        }
        else
        {
            Format(clientoption, sizeof(clientoption), "%s [%t]", clientoption, "Human");
        }

        // Add option to menu.
        menu_infect_clients.AddItem(clientuserid, clientoption);
    }

    Format(title, sizeof(title), "%t\n ", "Infect menu clients title");
    menu_infect_clients.SetTitle(title);

    // Create a "Back" button to the main admin menu.
    menu_infect_clients.ExitBackButton = true;

    // Send menu.
    menu_infect_clients.Display(client, MENU_TIME_FOREVER);
}

/**
 * Called when client selects option in the infect clients menu, and handles it.
 * @param menu_infect_clients   Handle of the menu being used.
 * @param action                The action done on the menu (see menus.inc, enum MenuAction).
 * @param client                The client index.
 * @param slot                  The slot index selected (starting from 0).
 */
public int InfectMenuClientsHandle(Menu menu_infect_clients, MenuAction action, int client, int slot)
{
    // Client selected an option.
    if (action == MenuAction_Select)
    {
        // Get selected client index.
        int target = MenuGetClientIndex(menu_infect_clients, slot);

        // If target has left the server, then stop.
        if (!target)
        {
            // Re-send menu.
            InfectMenuClients(client);
            return -1;
        }

        // Create an array with a single slot and set target to it.
        int targets[1];
        targets[0] = target;

        // Toggle infect on the client.
        if (InfectIsClientInfected(target))
        {
            InfectManualHuman(client, targets, 1);
        }
        else
        {
            InfectManualInfect(client, targets, 1);
        }

        // Re-send menu.
        InfectMenuClients(client);
    }
    // Client closed the menu.
    if (action == MenuAction_Cancel)
    {
        // Client hit "Back" button.
        if (slot == MenuCancel_ExitBack)
        {
            // Re-open admin menu.
            ZAdminMenu(client);
        }
    }
    // Client hit "Exit" button.
    else if (action == MenuAction_End)
    {
        delete menu_infect_clients;
    }
    return -1;
}

bool InfectHasZombieSpawned()
{
    return g_bZombieSpawned;
}

/**
 * Returns if a client is mother infected.
 *
 * @param client    The client index.
 * @return          True if the client has been mother infected, false otherwise.
 */
bool InfectIsClientMotherInfected(int client)
{
    // If client is invalid, then stop.
    if (!ZRIsClientValid(client))
    {
        return false;
    }

    // Return client's zombie flag.
    return g_bInfectMotherLast[client];
}

/**
 * Returns if a client is infected.
 * 
 * @param client	The client index.
 * @return		  True if the client has been infected, false otherwise.
 */	
bool InfectIsClientInfected(int client)
{
    // If client is invalid, then stop.
    if (!ZRIsClientValid(client))
    {
        return false;
    }

    // Return client's zombie flag.
    return g_bZombie[client];
}

/**
 * Returns if a client is a human.
 *
 * @param client    The client index.
 * @return          True if the client is a human, false otherwise.
 */
bool InfectIsClientHuman(int client)
{
    // If client is invalid, then stop.
    if (!ZRIsClientValid(client))
    {
        return true;
    }

    // Return opposite of client's zombie flag.
    return !g_bZombie[client];
}

/**
 * Infecting a client manually (via zr_infect or the "Zombie Management" menu)
 *
 * @param client            The client index infecting another client.
 * @param targets           Array containing all clients to infect.
 * @param count             The number of clients in the array.
 * @param respawnoverride   (Optional) True to override respawn cvar.
 * @param respawn           (Optional) True to respawn client on infect.
 */
stock void InfectManualInfect(int client, int[] targets, int count, bool respawnoverride = false, bool respawn = false)
{
    if (!g_bRoundFullyStarted)
    {
        TranslationReplyToCommand(client, "Infect command round not started");
        return;
    }

    bool zombiespawned = InfectHasZombieSpawned();

    // If zombie hasn't spawned, then make targetted player(s) mother zombies.
    if (!zombiespawned)
    {
        // Stop mother infect timer.
        if (g_tInfect != null)
        {
            KillTimer(g_tInfect);
            g_tInfect = null;
        }

        // Move all clients to CT
        for (int x = 1; x <= MaxClients; x++)
        {
            // If client isn't in-game, then stop.
            if (!IsClientInGame(x))
            {
                continue;
            }

            // If client is dead, then stop.
            if (!IsPlayerAlive(x))
            {
                continue;
            }

            // Switch client to CT team.
            CS_SwitchTeam(x, CS_TEAM_CT);
        }

        // Tell the plugin a mother zombie has spawned.
        g_bZombieSpawned = true;
    }

    char targetname[MAX_NAME_LENGTH];
    char adminname[MAX_NAME_LENGTH];

    // Get admin's name for later use.
    if (client > 0)
        GetClientName(client, adminname, sizeof(adminname));
    else
        strcopy(adminname, sizeof(adminname), "Console");

    bool success = false;

    // x = Client index.
    for (int x = 0; x < count; x++)
    {
        // Get client's name for later use.
        GetClientName(targets[x], targetname, sizeof(targetname));

        // Check if client is a human before turning into zombie.
        if (!InfectIsClientHuman(targets[x]))
        {
            continue;
        }

        // If zombie hasn't spawned, then make targetted player(s) mother zombies.
        if (!zombiespawned)
        {
            // Turn client into a mother zombie.
            InfectHumanToZombie(targets[x], _, true, respawnoverride, respawn);

            // Log action to game events.
            LogEvent(false, LogType_Normal, LOG_GAME_EVENTS, LogModule_Infect, "Manual Infect", "\"%L\" turned \"%L\" into a mother zombie", client, targets[x]);
            LogAction(client, -1, "[ZR] \"%L\" turned \"%L\" into a mother zombie.", client, targets[x]);

            success = true;
            continue;
        }

        // Turn client into a zombie.
        InfectHumanToZombie(targets[x], _, false, respawnoverride, respawn);

        // Log action to game events.
        LogEvent(false, LogType_Normal, LOG_GAME_EVENTS, LogModule_Infect, "Manual Infect", "\"%L\" turned \"%L\" into a zombie", client, targets[x]);
        LogAction(client, -1, "[ZR] \"%L\" turned \"%L\" into a zombie.", client, targets[x]);

        success = true;
    }

    // Tell admin the outcome of the command.
    if (success)
    {
        if (!zombiespawned)
        {
            TranslationReplyToCommand(client, "Infect command infect mother successful", targetname);
            TranslationPrintToChatAllExcept(false, false, client, "Infect command infect mother successful public", adminname, targetname);
        }
        else
        {
            TranslationReplyToCommand(client, "Infect command infect successful", targetname);
            TranslationPrintToChatAllExcept(false, false, client, "Infect command infect successful public", adminname, targetname);
        }
    }
    else
    {
        // Tell admin command was unsuccessful.
        TranslationReplyToCommand(client, "Infect command infect unsuccessful", targetname);
    }
}

/**
 * Infecting a client manually (via zr_human or the "Zombie Management" menu)
 *
 * @param client    The client index changing a zombie to human.
 * @param targets   Array containing all clients to make human.
 * @param count     The number of clients in the array.
 * @param respawn   (Optional) True to respawn client upon changing to human.
 * @param protect   (Optional) True to protect client upon changing to human.
 */
stock void InfectManualHuman(int client, int[] targets, int count, bool respawn = false, bool protect = false)
{
    char targetname[MAX_NAME_LENGTH];
    char adminname[MAX_NAME_LENGTH];

    // Get admin's name for later use.
    if (client > 0)
        GetClientName(client, adminname, sizeof(adminname));
    else
        strcopy(adminname, sizeof(adminname), "Console");

    bool success = false;

    // x = Client index.
    for (int x = 0; x < count; x++)
    {
        // Get client's name for later use.
        GetClientName(targets[x], targetname, sizeof(targetname));

        // Check if client is a human before turning into zombie.
        if (InfectIsClientInfected(targets[x]))
        {
            // Turn client into a zombie.
            InfectZombieToHuman(targets[x], respawn, protect);

            // Log action to game events.
            LogEvent(false, LogType_Normal, LOG_GAME_EVENTS, LogModule_Infect, "Manual Human", "\"%L\" turned \"%L\" into a human", client, targets[x]);
            LogAction(client, -1, "[ZR] \"%L\" turned \"%L\" into a human.", client, targets[x]);

            success = true;
        }
    }

    // Tell admin the outcome of the command.
    if (success)
    {
        TranslationReplyToCommand(client, "Infect command human successful", targetname);
        TranslationPrintToChatAllExcept(false, false, client, "Infect command human successful public", adminname, targetname);
    }
    else
    {
        TranslationReplyToCommand(client, "Infect command human unsuccessful", targetname);
    }
}

/**
 * Command callback (zr_infect)
 * Infects a client.
 *
 * @param client    The client index.
 * @param argc      Argument count.
 */
public Action InfectInfectCommand(int client, int argc)
{
    // Check if privileged.
    if (!ZRIsClientPrivileged(client, OperationType_Generic))
    {
        TranslationReplyToCommand(client, "No access to command");
        return Plugin_Handled;
    }

    // If not enough arguments given, then stop.
    if (argc < 1)
    {
        TranslationReplyToCommand(client, "Infect command infect syntax");
        return Plugin_Handled;
    }

    char target[MAX_NAME_LENGTH], targetname[MAX_NAME_LENGTH];
    int targets[MAXPLAYERS], result;
    bool tn_is_ml;

    // Get targetname.
    GetCmdArg(1, target, sizeof(target));

    // Find a target.
    result = ProcessTargetString(target, client, targets, sizeof(targets), COMMAND_FILTER_ALIVE | COMMAND_FILTER_NO_IMMUNITY, targetname, sizeof(targetname), tn_is_ml);

    // Check if there was a problem finding a client.
    if (result <= 0)
    {
        ZRReplyToTargetError(client, result);
        return Plugin_Handled;
    }

    // Get respawn parameter.
    char strRespawn[8];
    GetCmdArg(2, strRespawn, sizeof(strRespawn));

    bool respawnoverride, respawn;

    // If parameter exists then cast it into a bool and feed it to infect function.
    if (strRespawn[0])
    {
        respawnoverride = true;
        respawn = view_as<bool>(StringToInt(strRespawn));
    }

    // Infect player.
    InfectManualInfect(client, targets, result, respawnoverride, respawn);

    return Plugin_Handled;
}

/**
 * Command callback (zr_human)
 * Turns a client into a human.
 *
 * @param client    The client index.
 * @param argc      Argument count.
 */
public Action InfectHumanCommand(int client, int argc)
{
    // Check if privileged.
    if (!ZRIsClientPrivileged(client, OperationType_Generic))
    {
        TranslationReplyToCommand(client, "No access to command");
        return Plugin_Handled;
    }

    // If not enough arguments given, then stop.
    if (argc < 1)
    {
        TranslationReplyToCommand(client, "Infect command human syntax");
        return Plugin_Handled;
    }

    char target[MAX_NAME_LENGTH], targetname[MAX_NAME_LENGTH];
    int targets[MAXPLAYERS], result;
    bool tn_is_ml;

    // Get targetname.
    GetCmdArg(1, target, sizeof(target));

    // Find a target.
    result = ProcessTargetString(target, client, targets, sizeof(targets), COMMAND_FILTER_ALIVE | COMMAND_FILTER_NO_IMMUNITY, targetname, sizeof(targetname), tn_is_ml);

    // Check if there was a problem finding a client.
    if (result <= 0)
    {
        ZRReplyToTargetError(client, result);
        return Plugin_Handled;
    }

    // Get respawn&protect parameters
    char strRespawn[8], strProtect[8];
    GetCmdArg(2, strRespawn, sizeof(strRespawn));
    GetCmdArg(3, strProtect, sizeof(strProtect));

    // If parameter exists then cast it into a bool and feed it to "humanize" function.
    bool respawn = (strRespawn[0]) ? (view_as<bool>(StringToInt(strRespawn))) : false;
    bool protect = (strProtect[0]) ? (view_as<bool>(StringToInt(strProtect))) : false;

    // Turn client into human.
    InfectManualHuman(client, targets, result, respawn, protect);

    return Plugin_Handled;
}

/**
 * Converts a string to an infection mode.
 *
 * @param mode      Mode string to convert.
 *
 * @return          Infection mode or InfectMode_Invalid on error.
 */
InfectMode InfectStringToMode(const char[] mode)
{
    if (strlen(mode) == 0)
    {
        return InfectMode_Invalid;
    }

    if (strcmp(mode, "dynamic", false) == 0)
    {
        return InfectMode_Dynamic;
    }
    else if (strcmp(mode, "absolute", false) == 0)
    {
        return InfectMode_Absolute;
    }
    else if (strcmp(mode, "range", false) == 0)
    {
        return InfectMode_Range;
    }

    return InfectMode_Invalid;
}

/**
 * Gets and validates the infection mode. On error it will log a warning.
 *
 * @return  Infection mode or InfectMode_Invalid on error.
 */
InfectMode InfectGetModeOrFail()
{
    char modeName[16];
    g_hCvarsList.CVAR_INFECT_MZOMBIE_MODE.GetString(modeName, sizeof(modeName));

    InfectMode mode = InfectStringToMode(modeName);
    int ratio = g_hCvarsList.CVAR_INFECT_MZOMBIE_RATIO.IntValue;
    int min = g_hCvarsList.CVAR_INFECT_MZOMBIE_MIN.IntValue;
    int max = g_hCvarsList.CVAR_INFECT_MZOMBIE_MAX.IntValue;

    // Validate.
    switch (mode)
    {
        case InfectMode_Invalid:
        {
            LogEvent(false, LogType_Error, LOG_CORE_EVENTS, LogModule_Infect, "Config Validation", "Warning: Invalid infection mode (\"%s\"). Falling back to one mother zombie.", modeName);
        }
        case InfectMode_Dynamic:
        {
            if (ratio < 0)
            {
                LogEvent(false, LogType_Error, LOG_CORE_EVENTS, LogModule_Infect, "Config Validation", "Warning: Invalid infection ratio (\"%d\"). Must be zero or positive in dynamic mode. Falling back to one mother zombie.", ratio);
                return InfectMode_Invalid;
            }
        }
        case InfectMode_Absolute:
        {
            if (ratio == 0)
            {
                LogEvent(false, LogType_Error, LOG_CORE_EVENTS, LogModule_Infect, "Config Validation", "Warning: Invalid infection ratio (\"%d\"). Must be nonzero in absolute mode. Falling back to one mother zombie.", ratio);
                return InfectMode_Invalid;
            }
        }
        case InfectMode_Range:
        {
            bool failed = false;
            if (min <= 0)
            {
                LogEvent(false, LogType_Error, LOG_CORE_EVENTS, LogModule_Infect, "Config Validation", "Warning: Invalid infection range (\"%d\"). Cvar zr_infect_mzombie_min must be nonzero and positive. Falling back to one mother zombie.", min);
                failed = true;
            }
            if (max <= 0)
            {
                LogEvent(false, LogType_Error, LOG_CORE_EVENTS, LogModule_Infect, "Config Validation", "Warning: Invalid infection range (\"%d\"). Cvar zr_infect_mzombie_max must be nonzero and positive. Falling back to one mother zombie.", max);
                failed = true;
            }
            if (min > max || max < min)
            {
                LogEvent(false, LogType_Error, LOG_CORE_EVENTS, LogModule_Infect, "Config Validation", "Warning: Infection range values are overlapping or reversed. Check zr_infect_mzombie_min and zr_infect_mzombie_min. Falling back to one mother zombie.");
                failed = true;
            }

            if (failed)
            {
                return InfectMode_Invalid;
            }
        }
    }

    return mode;
}

/**
 * Resets all mother zombie overrides to their default state.
 * Call this function to clear all stored overrides.
 */
void ResetMotherZombieOverrides()
{
    for (MotherZombieOverrideAttr i = MZOVR_HEALTH; i < MZOVR_COUNT; i++)
    {
        g_MotherZombieOverrideTypes[i] = MZ_OVERRIDE_NONE;
        g_MotherZombieOverrideIntValues[i] = 0;
        g_MotherZombieOverrideFloatValues[i] = 0.0;
        g_MotherZombieOverrideStringValues[i][0] = '\0';
    }
}
